/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'robbie' at '11/18/15 11:09 PM' with Gradle 2.9
 *
 * @author robbie, @date 11/18/15 11:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
